### Health check
GET http://localhost:3000/

### Example A
POST http://localhost:3000/bfhl
Content-Type: application/json

{
  "data": ["a","1","334","4","R","$"]
}

### Example B
POST http://localhost:3000/bfhl
Content-Type: application/json

{
  "data": ["2","a","y","4","&","-","*","5","92","b"]
}

### Example C
POST http://localhost:3000/bfhl
Content-Type: application/json

{
  "data": ["A","ABcD","DOE"]
}
